development:
  adapter: postgresql
  database: restate_development
  username: neo
  password: neo
  host: localhost

test:
  adapter: postgresql
  database: restate_test
  username: neo
  password: neo
  host: localhost

